// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"try-go-vercels/app/handlers"
	"try-go-vercels/app/repositories"
	"try-go-vercels/app/services"
)

// Injectors from wire.go:

func InitializeHandler() *handlers.Handler {
	repository := repositories.NewRepository()
	service := services.NewService(repository)
	handler := handlers.NewHandler(service)
	return handler
}
